<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>WebScrapingRebuilder</AssemblyName>
    <RootNamespace>WebScrapingRebuilder</RootNamespace>

    <!-- 发布：仅 Windows x64、单文件、不启用 AOT、依赖库(框架依赖)模式以减小 EXE 体积 -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishAot>false</PublishAot>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebugType>none</DebugType>
  </PropertyGroup>

</Project>
